language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: 3aacfe8b5b095d54ca2128a4bc103641 ##Chiave generale
    token: 1c40c43acbfbca98e26b9b7b7a119abb0f0dce04 ##Chiave travis


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GlaAndry_Deliverable2